server:
    port: 8010
spring:
    application:
        name: consumer-movie-ribbon
eureka:
    client:
        serviceUrl:
            defaultZone: http://cluster1:8761/eureka/,http://cluster2:8762/eureka/
    instance:
        preferIpAddress: true
