server:
    port: 8040
spring:
    application:
        name: microservice-config-server
    cloud:
        config:
            server:
                git:
                    uri: /home/cmonkey/Dropbox/repos/config-repo.git
                    label: develop
                    #search-paths: config-repo
                    username:
                    password: 
            
