server:
    port: 8040
spring:
    application:
        name: microservice-config-server
    cloud:
        config:
            git:
                url: ~/Dropbox/repos/microservice/
                search-paths: config-repo
                username:
                password: 
            
