drop table  user if exists;
create table user (id bigint generated by default as identity, username varchar(255), age int, primary key (id));

drop table plat_form_data if exists;
CREATE TABLE `plat_form_data` (
  id bigint(20) generated by default as IDENTITY ,
  `create_Time` datetime ,
  `reg_Count` bigint(6) ,
  `bank_Count` bigint(4) ,
  `invest_Count_Or_Day` bigint(10),
  `invest_Count` bigint(4) ,
  `invest_New_Count` bigint(4) ,
  `invest_Sum` decimal(18,2),
  `annual_Sum` decimal(18,2) ,
  `invest_Convert` decimal(18,2),
  `recharge_Sum` decimal(18,2) ,
  `cash_With_Sum` decimal(18,2) ,
  `repayment_Sum` decimal(18,2) ,
  `interest_Sum` decimal(18,2) ,
  `collect_Sum` decimal(18,2) ,
  `red_Sum` decimal(18,2) ,
  `cash_Sum` decimal(18,2) ,
  `origin_Invest_Count` bigint(6) ,
  `origin_Invest_Sum` decimal(18,2) ,
  PRIMARY KEY (`id`)
)

